// /app/layout.tsx
import type React from "react";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"; //トースト機能を実現するToasterインポート;
import "./globals.css";

export const metadata: Metadata = {
  title: "学習記録アプリ with Firebase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/* Tailwind CSSのCSS設定を指定 */}
      <body className="min-h-screen bg-background font-sans antialiased">
        {children}
        {/* トースト機能を実現するToasterコンポーネントを配置 */}
        <Toaster position="top-center" theme="dark" />
      </body>
    </html>
  );
}
